---
- name: Ensure there are 3 nodes in our OpenStack
  hosts: localhost
  become: no
  tasks:

  - name: Ensure my-security-group security group exists to allow traffic between nodes
    openstack.cloud.security_group:
      state: present
      name: my-security-group
      description: My Security Group

  - name: Ensure there are servers
    openstack.cloud.server:
      state: present
      auth:
        auth_url: "{{ os_auth_url }}"
        username: "{{ os_auth_user }}"
        password: "{{ os_auth_pass }}"
        project_name: "{{ os_auth_project_name }}"
        project_domain_name: "{{ os_project_domain_name }}"
        user_domain_name: "{{ os_user_domain_name }}"
      name: "{{ item.name }}"
      image: CentOS-7
      key_name: my_pubkey_in_openstack
      timeout: 200
      flavor: standard.tiny
      network: project_name
      meta:
        hostname: "{{ item.name }}"
        group: my_example_group
      userdata: ''
      security_groups:
        - my-security-group
      floating_ips: "{{ item.floating_ip }}"
    with_items: "{{ virtual_servers }}"
    register: instances

  - name: Ensure security group rule to allow TCP internal traffic between nodes exists
    openstack.cloud.security_group_rule:
      security_group: my-security-group
      protocol: tcp
      port_range_min: 1
      port_range_max: 65535
      remote_ip_prefix: "{{ item['openstack']['private_v4'] }}"
    with_items: "{{ instances['results'] }}"

  - name: Ensure security group rule to allow ICMP internal traffic between nodes exists
    openstack.cloud.security_group_rule:
      security_group: my-security-group
      protocol: icmp
      remote_ip_prefix: "{{ item['openstack']['private_v4'] }}"
    with_items: "{{ instances['results'] }}"